# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v6.0.0'
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: destroyed-symlinks
    - id: detect-private-key
    - id: check-ast
    - id: check-case-conflict
    - id: debug-statements
    - id: forbid-submodules
    - id: check-symlinks
    - id: check-shebang-scripts-are-executable
    - id: check-case-conflict
    - id: check-added-large-files
      args: ['--maxkb=4096']
    - id: destroyed-symlinks
    - id: double-quote-string-fixer
    - id: mixed-line-ending
      args: ['--fix=lf']

# YAPF and flake8 need to remain pinned.
- repo: https://github.com/google/yapf
  rev: 'v0.43.0' # frozen 'v0.43.0'
  hooks:
    - id: yapf
      additional_dependencies: ['toml']

- repo: https://github.com/pycqa/flake8
  rev: '7.3.0' # frozen '7.3.0'
  hooks:
    - id: flake8
      additional_dependencies: ['flake8-docstrings']

- repo: https://github.com/PyCQA/bandit
  rev: '1.9.4'
  hooks:
    - id: bandit
      args: ['-c', 'pyproject.toml', '--level', 'LOW']
      additional_dependencies: ['bandit[toml]']

- repo: https://github.com/pycqa/isort
  rev: '9.0.0a3'
  hooks:
    - id: isort

- repo: https://github.com/asottile/pyupgrade
  rev: 'v3.15.0'
  hooks:
    - id: pyupgrade

- repo: https://codeberg.org/frnmst/md-toc
  rev: '9.0.0'
  hooks:
    - id: md-toc
      args: ['-p', 'cmark', '-l6']

- repo: https://github.com/jorisroovers/gitlint
  rev: 'v0.19.1'
  hooks:
    - id: gitlint

- repo: https://github.com/ljnsn/cz-conventional-gitmoji
  rev: 'v0.7.0'
  hooks:
    - id: conventional-gitmoji
